node('master') 
{
    stage('ContinuousDownload')
    {
       git 'https://github.com/subodh6/subo.git'
    }
    stage('ContinuousBuild')
    {
       sh 'mvn package'
    }
    stage('ContinuousDeployment')
    {
        sh 'scp /home/ubuntu/.jenkins/workspace/multibranch/webapp/target/webapp.war ubuntu@172.31.29.82:/var/lib/tomcat7/webapps/qaenv.war'
    }
}
